server:
  port: 3344

spring:
  application:
    name: cloud-config-center3344 # 注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huanghuigh/springcloud-config.git #GitHub上面的git仓库名称
        #### 搜索目录
          search-paths:
            - springcloud-config
      #### 读取分支
      label: master

# rabbitmq相关配置
  rabbitmq:
    host: 47.95.205.133
    port: 5672
    username: guangtou
    password: guangtou



# rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

# 服务注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
