server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动图创建路由的功能,利用微服务名进行路由
      routes:
        - id: payment_routh # payment_router    # 路由的Id,没有固定规则但是要求唯一,建议配合服务名
#          uri: http://localhost:8001            # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**              # 断言,路径相匹配的进行路由
#            - After=2020-05-08T08:50:51.674+08:00[Asia/Shanghai] # after,在此时间后
#            - Between=2020-05-08T09:50:51.674+08:00[Asia/Shanghai],2020-05-18T09:50:51.674+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy # 需要携带cookie才能访问
        - id: payment_routh2 # payment_router2    # 路由的Id,没有固定规则但是要求唯一,建议配合服务名
#          uri: http://localhost:8001            # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**              # 断言,路径相匹配的进行路由
            - Header=X-Request-Id, \d+ # 请求头要有X-Request-Id属性,并且值为整数的正则表达式
eureka:
  instance:
    hostname: cloud-gateway-service
  client: # 服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka