server:
  port: 80

eureka:
  client:
    register-with-eureka: false # 不将自己注册进EurekaServer
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka

# 设置feign客户端超时时间(Openfeign默认支持Ribbon)
ribbon:
  # 设置建立连接所用的时间,两端连接所用时间
  ReadTimeout: 5000
  # 建立连接后服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

# 设置service.PaymentFeignService路径下日志级别为debug,方便Feign日志输出查看
logging:
  level:
    show.huanghui.cloudstudy.service.PaymentFeignService: debug

