server:
  port: 8001
spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
#    注册到Eureka地址
    service-url:
      defaultZone: http://localhost:7001/eureka/
